image:
  - Visual Studio 2017
  - Ubuntu

stack: jdk 8
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  nodejs_version: "8"
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  CLIENTTESTS_XRAY_URL:
    secure: qgCv/IbOkjDfFcgdtMdM46XkDrFdjNKPvqMsCKRk4Ko=
  CLIENTTESTS_XRAY_USERNAME:
    secure: qr5vtfCwBPUAQyCqU2/0tQ==
  CLIENTTESTS_XRAY_PASSWORD:
    secure: um65vfntLOx1gsOA4oo1Bg4/aEVR7JdNTJSZc8/jPl3h0b5mN1TBpKsHUywfx31tqGR9nwwb32zT4QQG/Jhjyhe+M+loJtN8hqlby+iefnk=

test_script:
  - sh: ./gradlew test
  - cmd: gradlew.bat test

# Don't actually build.
build: off